// Automatically generated by makemoduledefs.py.

#include "mpconfig.h"
#if (CIRCUITPY_BLEIO)
    extern const struct _mp_obj_module_t bleio_module;
    #define MODULE_DEF_MP_QSTR__BLEIO { MP_ROM_QSTR(MP_QSTR__bleio), MP_ROM_PTR(&bleio_module) },
#else
    #define MODULE_DEF_MP_QSTR__BLEIO
#endif

#if (CIRCUITPY_BUSDEVICE)
    extern const struct _mp_obj_module_t adafruit_bus_device_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE { MP_ROM_QSTR(MP_QSTR_adafruit_bus_device), MP_ROM_PTR(&adafruit_bus_device_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE
#endif

#if (CIRCUITPY_PIXELBUF)
    extern const struct _mp_obj_module_t pixelbuf_module;
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF { MP_ROM_QSTR(MP_QSTR_adafruit_pixelbuf), MP_ROM_PTR(&pixelbuf_module) },
#else
    #define MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF
#endif

#if (CIRCUITPY_AESIO)
    extern const struct _mp_obj_module_t aesio_module;
    #define MODULE_DEF_MP_QSTR_AESIO { MP_ROM_QSTR(MP_QSTR_aesio), MP_ROM_PTR(&aesio_module) },
#else
    #define MODULE_DEF_MP_QSTR_AESIO
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_array;
    #define MODULE_DEF_MP_QSTR_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },
#else
    #define MODULE_DEF_MP_QSTR_ARRAY
#endif

#if (CIRCUITPY_ATEXIT)
    extern const struct _mp_obj_module_t atexit_module;
    #define MODULE_DEF_MP_QSTR_ATEXIT { MP_ROM_QSTR(MP_QSTR_atexit), MP_ROM_PTR(&atexit_module) },
#else
    #define MODULE_DEF_MP_QSTR_ATEXIT
#endif

#if (MICROPY_PY_UBINASCII)
    extern const struct _mp_obj_module_t mp_module_ubinascii;
    #define MODULE_DEF_MP_QSTR_BINASCII { MP_ROM_QSTR(MP_QSTR_binascii), MP_ROM_PTR(&mp_module_ubinascii) },
#else
    #define MODULE_DEF_MP_QSTR_BINASCII
#endif

#if (CIRCUITPY_BITBANGIO)
    extern const struct _mp_obj_module_t bitbangio_module;
    #define MODULE_DEF_MP_QSTR_BITBANGIO { MP_ROM_QSTR(MP_QSTR_bitbangio), MP_ROM_PTR(&bitbangio_module) },
#else
    #define MODULE_DEF_MP_QSTR_BITBANGIO
#endif

#if (CIRCUITPY_BITMAPTOOLS)
    extern const struct _mp_obj_module_t bitmaptools_module;
    #define MODULE_DEF_MP_QSTR_BITMAPTOOLS { MP_ROM_QSTR(MP_QSTR_bitmaptools), MP_ROM_PTR(&bitmaptools_module) },
#else
    #define MODULE_DEF_MP_QSTR_BITMAPTOOLS
#endif

#if (CIRCUITPY_BOARD)
    extern const struct _mp_obj_module_t board_module;
    #define MODULE_DEF_MP_QSTR_BOARD { MP_ROM_QSTR(MP_QSTR_board), MP_ROM_PTR(&board_module) },
#else
    #define MODULE_DEF_MP_QSTR_BOARD
#endif

#if (CIRCUITPY_BUSIO)
    extern const struct _mp_obj_module_t busio_module;
    #define MODULE_DEF_MP_QSTR_BUSIO { MP_ROM_QSTR(MP_QSTR_busio), MP_ROM_PTR(&busio_module) },
#else
    #define MODULE_DEF_MP_QSTR_BUSIO
#endif

#if (CIRCUITPY_DIGITALIO)
    extern const struct _mp_obj_module_t digitalio_module;
    #define MODULE_DEF_MP_QSTR_DIGITALIO { MP_ROM_QSTR(MP_QSTR_digitalio), MP_ROM_PTR(&digitalio_module) },
#else
    #define MODULE_DEF_MP_QSTR_DIGITALIO
#endif

#if (CIRCUITPY_DISPLAYIO)
    extern const struct _mp_obj_module_t displayio_module;
    #define MODULE_DEF_MP_QSTR_DISPLAYIO { MP_ROM_QSTR(MP_QSTR_displayio), MP_ROM_PTR(&displayio_module) },
#else
    #define MODULE_DEF_MP_QSTR_DISPLAYIO
#endif

#if (MICROPY_PY_UERRNO)
    extern const struct _mp_obj_module_t mp_module_uerrno;
    #define MODULE_DEF_MP_QSTR_ERRNO { MP_ROM_QSTR(MP_QSTR_errno), MP_ROM_PTR(&mp_module_uerrno) },
#else
    #define MODULE_DEF_MP_QSTR_ERRNO
#endif

#if (CIRCUITPY_DISPLAYIO && CIRCUITPY_TERMINALIO)
    extern const struct _mp_obj_module_t fontio_module;
    #define MODULE_DEF_MP_QSTR_FONTIO { MP_ROM_QSTR(MP_QSTR_fontio), MP_ROM_PTR(&fontio_module) },
#else
    #define MODULE_DEF_MP_QSTR_FONTIO
#endif

#if (CIRCUITPY_FRAMEBUFFERIO)
    extern const struct _mp_obj_module_t framebufferio_module;
    #define MODULE_DEF_MP_QSTR_FRAMEBUFFERIO { MP_ROM_QSTR(MP_QSTR_framebufferio), MP_ROM_PTR(&framebufferio_module) },
#else
    #define MODULE_DEF_MP_QSTR_FRAMEBUFFERIO
#endif

#if (CIRCUITPY_GETPASS)
    extern const struct _mp_obj_module_t getpass_module;
    #define MODULE_DEF_MP_QSTR_GETPASS { MP_ROM_QSTR(MP_QSTR_getpass), MP_ROM_PTR(&getpass_module) },
#else
    #define MODULE_DEF_MP_QSTR_GETPASS
#endif

#if (CIRCUITPY_GIFIO)
    extern const struct _mp_obj_module_t gifio_module;
    #define MODULE_DEF_MP_QSTR_GIFIO { MP_ROM_QSTR(MP_QSTR_gifio), MP_ROM_PTR(&gifio_module) },
#else
    #define MODULE_DEF_MP_QSTR_GIFIO
#endif

#if (MICROPY_PY_UJSON)
    extern const struct _mp_obj_module_t mp_module_ujson;
    #define MODULE_DEF_MP_QSTR_JSON { MP_ROM_QSTR(MP_QSTR_json), MP_ROM_PTR(&mp_module_ujson) },
#else
    #define MODULE_DEF_MP_QSTR_JSON
#endif

#if (CIRCUITPY_KEYPAD)
    extern const struct _mp_obj_module_t keypad_module;
    #define MODULE_DEF_MP_QSTR_KEYPAD { MP_ROM_QSTR(MP_QSTR_keypad), MP_ROM_PTR(&keypad_module) },
#else
    #define MODULE_DEF_MP_QSTR_KEYPAD
#endif

#if (CIRCUITPY_MATH)
    extern const struct _mp_obj_module_t math_module;
    #define MODULE_DEF_MP_QSTR_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&math_module) },
#else
    #define MODULE_DEF_MP_QSTR_MATH
#endif

#if (CIRCUITPY_MICROCONTROLLER)
    extern const struct _mp_obj_module_t microcontroller_module;
    #define MODULE_DEF_MP_QSTR_MICROCONTROLLER { MP_ROM_QSTR(MP_QSTR_microcontroller), MP_ROM_PTR(&microcontroller_module) },
#else
    #define MODULE_DEF_MP_QSTR_MICROCONTROLLER
#endif

#if (CIRCUITPY_MSGPACK)
    extern const struct _mp_obj_module_t msgpack_module;
    #define MODULE_DEF_MP_QSTR_MSGPACK { MP_ROM_QSTR(MP_QSTR_msgpack), MP_ROM_PTR(&msgpack_module) },
#else
    #define MODULE_DEF_MP_QSTR_MSGPACK
#endif

#if (CIRCUITPY_NEOPIXEL_WRITE)
    extern const struct _mp_obj_module_t neopixel_write_module;
    #define MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE { MP_ROM_QSTR(MP_QSTR_neopixel_write), MP_ROM_PTR(&neopixel_write_module) },
#else
    #define MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE
#endif

#if (CIRCUITPY_ONEWIREIO)
    extern const struct _mp_obj_module_t onewireio_module;
    #define MODULE_DEF_MP_QSTR_ONEWIREIO { MP_ROM_QSTR(MP_QSTR_onewireio), MP_ROM_PTR(&onewireio_module) },
#else
    #define MODULE_DEF_MP_QSTR_ONEWIREIO
#endif

#if (CIRCUITPY_OS)
    extern const struct _mp_obj_module_t os_module;
    #define MODULE_DEF_MP_QSTR_OS { MP_ROM_QSTR(MP_QSTR_os), MP_ROM_PTR(&os_module) },
#else
    #define MODULE_DEF_MP_QSTR_OS
#endif

#if (CIRCUITPY_RAINBOWIO)
    extern const struct _mp_obj_module_t rainbowio_module;
    #define MODULE_DEF_MP_QSTR_RAINBOWIO { MP_ROM_QSTR(MP_QSTR_rainbowio), MP_ROM_PTR(&rainbowio_module) },
#else
    #define MODULE_DEF_MP_QSTR_RAINBOWIO
#endif

#if (CIRCUITPY_RANDOM)
    extern const struct _mp_obj_module_t random_module;
    #define MODULE_DEF_MP_QSTR_RANDOM { MP_ROM_QSTR(MP_QSTR_random), MP_ROM_PTR(&random_module) },
#else
    #define MODULE_DEF_MP_QSTR_RANDOM
#endif

#if (MICROPY_PY_URE)
    extern const struct _mp_obj_module_t mp_module_ure;
    #define MODULE_DEF_MP_QSTR_RE { MP_ROM_QSTR(MP_QSTR_re), MP_ROM_PTR(&mp_module_ure) },
#else
    #define MODULE_DEF_MP_QSTR_RE
#endif

#if (CIRCUITPY_SDCARDIO)
    extern const struct _mp_obj_module_t sdcardio_module;
    #define MODULE_DEF_MP_QSTR_SDCARDIO { MP_ROM_QSTR(MP_QSTR_sdcardio), MP_ROM_PTR(&sdcardio_module) },
#else
    #define MODULE_DEF_MP_QSTR_SDCARDIO
#endif

#if (CIRCUITPY_SDIOIO)
    extern const struct _mp_obj_module_t sdioio_module;
    #define MODULE_DEF_MP_QSTR_SDIOIO { MP_ROM_QSTR(MP_QSTR_sdioio), MP_ROM_PTR(&sdioio_module) },
#else
    #define MODULE_DEF_MP_QSTR_SDIOIO
#endif

#if (MICROPY_PY_USELECT)
    extern const struct _mp_obj_module_t mp_module_uselect;
    #define MODULE_DEF_MP_QSTR_SELECT { MP_ROM_QSTR(MP_QSTR_select), MP_ROM_PTR(&mp_module_uselect) },
#else
    #define MODULE_DEF_MP_QSTR_SELECT
#endif

#if (CIRCUITPY_SHARPDISPLAY)
    extern const struct _mp_obj_module_t sharpdisplay_module;
    #define MODULE_DEF_MP_QSTR_SHARPDISPLAY { MP_ROM_QSTR(MP_QSTR_sharpdisplay), MP_ROM_PTR(&sharpdisplay_module) },
#else
    #define MODULE_DEF_MP_QSTR_SHARPDISPLAY
#endif

#if (CIRCUITPY_STORAGE)
    extern const struct _mp_obj_module_t storage_module;
    #define MODULE_DEF_MP_QSTR_STORAGE { MP_ROM_QSTR(MP_QSTR_storage), MP_ROM_PTR(&storage_module) },
#else
    #define MODULE_DEF_MP_QSTR_STORAGE
#endif

#if (CIRCUITPY_STRUCT)
    extern const struct _mp_obj_module_t struct_module;
    #define MODULE_DEF_MP_QSTR_STRUCT { MP_ROM_QSTR(MP_QSTR_struct), MP_ROM_PTR(&struct_module) },
#else
    #define MODULE_DEF_MP_QSTR_STRUCT
#endif

#if (CIRCUITPY_SUPERVISOR)
    extern const struct _mp_obj_module_t supervisor_module;
    #define MODULE_DEF_MP_QSTR_SUPERVISOR { MP_ROM_QSTR(MP_QSTR_supervisor), MP_ROM_PTR(&supervisor_module) },
#else
    #define MODULE_DEF_MP_QSTR_SUPERVISOR
#endif

#if (CIRCUITPY_DISPLAYIO && CIRCUITPY_TERMINALIO)
    extern const struct _mp_obj_module_t terminalio_module;
    #define MODULE_DEF_MP_QSTR_TERMINALIO { MP_ROM_QSTR(MP_QSTR_terminalio), MP_ROM_PTR(&terminalio_module) },
#else
    #define MODULE_DEF_MP_QSTR_TERMINALIO
#endif

#if (CIRCUITPY_TIME)
    extern const struct _mp_obj_module_t time_module;
    #define MODULE_DEF_MP_QSTR_TIME { MP_ROM_QSTR(MP_QSTR_time), MP_ROM_PTR(&time_module) },
#else
    #define MODULE_DEF_MP_QSTR_TIME
#endif

#if (CIRCUITPY_TOUCHIO)
    extern const struct _mp_obj_module_t touchio_module;
    #define MODULE_DEF_MP_QSTR_TOUCHIO { MP_ROM_QSTR(MP_QSTR_touchio), MP_ROM_PTR(&touchio_module) },
#else
    #define MODULE_DEF_MP_QSTR_TOUCHIO
#endif

#if (CIRCUITPY_TRACEBACK)
    extern const struct _mp_obj_module_t traceback_module;
    #define MODULE_DEF_MP_QSTR_TRACEBACK { MP_ROM_QSTR(MP_QSTR_traceback), MP_ROM_PTR(&traceback_module) },
#else
    #define MODULE_DEF_MP_QSTR_TRACEBACK
#endif

#if (MODULE_ULAB_ENABLED)
    extern const struct _mp_obj_module_t ulab_user_cmodule;
    #define MODULE_DEF_MP_QSTR_ULAB { MP_ROM_QSTR(MP_QSTR_ulab), MP_ROM_PTR(&ulab_user_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_ULAB
#endif

#if (CIRCUITPY_USB_CDC)
    extern const struct _mp_obj_module_t usb_cdc_module;
    #define MODULE_DEF_MP_QSTR_USB_CDC { MP_ROM_QSTR(MP_QSTR_usb_cdc), MP_ROM_PTR(&usb_cdc_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_CDC
#endif

#if (CIRCUITPY_USB_HID)
    extern const struct _mp_obj_module_t usb_hid_module;
    #define MODULE_DEF_MP_QSTR_USB_HID { MP_ROM_QSTR(MP_QSTR_usb_hid), MP_ROM_PTR(&usb_hid_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_HID
#endif

#if (CIRCUITPY_USB_MIDI)
    extern const struct _mp_obj_module_t usb_midi_module;
    #define MODULE_DEF_MP_QSTR_USB_MIDI { MP_ROM_QSTR(MP_QSTR_usb_midi), MP_ROM_PTR(&usb_midi_module) },
#else
    #define MODULE_DEF_MP_QSTR_USB_MIDI
#endif

#if (CIRCUITPY_VECTORIO)
    extern const struct _mp_obj_module_t vectorio_module;
    #define MODULE_DEF_MP_QSTR_VECTORIO { MP_ROM_QSTR(MP_QSTR_vectorio), MP_ROM_PTR(&vectorio_module) },
#else
    #define MODULE_DEF_MP_QSTR_VECTORIO
#endif

#if (CIRCUITPY_VIDEOCORE)
    extern const struct _mp_obj_module_t videocore_module;
    #define MODULE_DEF_MP_QSTR_VIDEOCORE { MP_ROM_QSTR(MP_QSTR_videocore), MP_ROM_PTR(&videocore_module) },
#else
    #define MODULE_DEF_MP_QSTR_VIDEOCORE
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR__BLEIO \
    MODULE_DEF_MP_QSTR_ADAFRUIT_BUS_DEVICE \
    MODULE_DEF_MP_QSTR_ADAFRUIT_PIXELBUF \
    MODULE_DEF_MP_QSTR_AESIO \
    MODULE_DEF_MP_QSTR_ARRAY \
    MODULE_DEF_MP_QSTR_ATEXIT \
    MODULE_DEF_MP_QSTR_BINASCII \
    MODULE_DEF_MP_QSTR_BITBANGIO \
    MODULE_DEF_MP_QSTR_BITMAPTOOLS \
    MODULE_DEF_MP_QSTR_BOARD \
    MODULE_DEF_MP_QSTR_BUSIO \
    MODULE_DEF_MP_QSTR_DIGITALIO \
    MODULE_DEF_MP_QSTR_DISPLAYIO \
    MODULE_DEF_MP_QSTR_ERRNO \
    MODULE_DEF_MP_QSTR_FONTIO \
    MODULE_DEF_MP_QSTR_FRAMEBUFFERIO \
    MODULE_DEF_MP_QSTR_GETPASS \
    MODULE_DEF_MP_QSTR_GIFIO \
    MODULE_DEF_MP_QSTR_JSON \
    MODULE_DEF_MP_QSTR_KEYPAD \
    MODULE_DEF_MP_QSTR_MATH \
    MODULE_DEF_MP_QSTR_MICROCONTROLLER \
    MODULE_DEF_MP_QSTR_MSGPACK \
    MODULE_DEF_MP_QSTR_NEOPIXEL_WRITE \
    MODULE_DEF_MP_QSTR_ONEWIREIO \
    MODULE_DEF_MP_QSTR_OS \
    MODULE_DEF_MP_QSTR_RAINBOWIO \
    MODULE_DEF_MP_QSTR_RANDOM \
    MODULE_DEF_MP_QSTR_RE \
    MODULE_DEF_MP_QSTR_SDCARDIO \
    MODULE_DEF_MP_QSTR_SDIOIO \
    MODULE_DEF_MP_QSTR_SELECT \
    MODULE_DEF_MP_QSTR_SHARPDISPLAY \
    MODULE_DEF_MP_QSTR_STORAGE \
    MODULE_DEF_MP_QSTR_STRUCT \
    MODULE_DEF_MP_QSTR_SUPERVISOR \
    MODULE_DEF_MP_QSTR_TERMINALIO \
    MODULE_DEF_MP_QSTR_TIME \
    MODULE_DEF_MP_QSTR_TOUCHIO \
    MODULE_DEF_MP_QSTR_TRACEBACK \
    MODULE_DEF_MP_QSTR_ULAB \
    MODULE_DEF_MP_QSTR_USB_CDC \
    MODULE_DEF_MP_QSTR_USB_HID \
    MODULE_DEF_MP_QSTR_USB_MIDI \
    MODULE_DEF_MP_QSTR_VECTORIO \
    MODULE_DEF_MP_QSTR_VIDEOCORE \
// MICROPY_REGISTERED_MODULES
