// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "7.2.0-alpha.1-109-gfce6d16c8-dirty"
#define MICROPY_GIT_HASH "fce6d16c8-dirty"
#define MICROPY_BUILD_DATE "2022-01-15"
#define MICROPY_VERSION_MAJOR (7)
#define MICROPY_VERSION_MINOR (2)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_STRING "7.2.0"
#define MICROPY_FULL_VERSION_INFO "Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME
